#
#
## TESTS
#
#python3 -m test ed_airl --env MazeED --env_designs "demo" --out_path ed_airl_maze_run4 --timelimit 250 --timelimit_noise 10 --max_iter_airl 45 --max_iter_multi_airl=15 --max_iter_rl=35 --n_iter 10 --subset_size 10
#python3 -m test ed_airl --env MazeED --env_designs "demo" --out_path ed_airl_maze_run5 --timelimit 250 --timelimit_noise 10 --max_iter_airl 45 --max_iter_multi_airl=15 --max_iter_rl=35 --n_iter 10 --subset_size 10
##python3 -m test ed_airl --env MazeED --env_designs "demo" --out_path ed_airl_maze_run6 --timelimit 250 --timelimit_noise 10 --max_iter_airl 45 --max_iter_multi_airl=15 --max_iter_rl=35 --n_iter 10 --subset_size 10
#

python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_0/ed_airl_maze_run1/single_env_reward_function --name "ed_airl_maze_iter0" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
##python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_1/ed_airl_maze_run1/best_guess_reward_function --name "ed_airl_maze_iter1" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
##python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_2/ed_airl_maze_run1/best_guess_reward_function --name "ed_airl_maze_iter2" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
##python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_3/ed_airl_maze_run1/best_guess_reward_function --name "ed_airl_maze_iter3" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
##python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_4/ed_airl_maze_run1/best_guess_reward_function --name "ed_airl_maze_iter4" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
##python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_5/ed_airl_maze_run1/best_guess_reward_function --name "ed_airl_maze_iter5" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
##python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_6/ed_airl_maze_run1/best_guess_reward_function --name "ed_airl_maze_iter6" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
##python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_7/ed_airl_maze_run1/best_guess_reward_function --name "ed_airl_maze_iter7" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_8/ed_airl_maze_run1/best_guess_reward_function --name "ed_airl_maze_iter8" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
##python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_9/ed_airl_maze_run1/best_guess_reward_function --name "ed_airl_maze_iter9" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10

python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_0/ed_airl_maze_run2/single_env_reward_function --name "ed_airl_maze_iter0" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
##python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_1/ed_airl_maze_run2/best_guess_reward_function --name "ed_airl_maze_iter1" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
##python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_2/ed_airl_maze_run2/best_guess_reward_function --name "ed_airl_maze_iter2" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
##python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_3/ed_airl_maze_run2/best_guess_reward_function --name "ed_airl_maze_iter3" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
##python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_4/ed_airl_maze_run2/best_guess_reward_function --name "ed_airl_maze_iter4" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
##python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_5/ed_airl_maze_run2/best_guess_reward_function --name "ed_airl_maze_iter5" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
##python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_6/ed_airl_maze_run2/best_guess_reward_function --name "ed_airl_maze_iter6" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
##python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_7/ed_airl_maze_run2/best_guess_reward_function --name "ed_airl_maze_iter7" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_8/ed_airl_maze_run2/best_guess_reward_function --name "ed_airl_maze_iter8" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
##python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_9/ed_airl_maze_run2/best_guess_reward_function --name "ed_airl_maze_iter9" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10

python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_0/ed_airl_maze_run3/single_env_reward_function --name "ed_airl_maze_iter0" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_1/ed_airl_maze_run3/best_guess_reward_function --name "ed_airl_maze_iter1" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_2/ed_airl_maze_run3/best_guess_reward_function --name "ed_airl_maze_iter2" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_3/ed_airl_maze_run3/best_guess_reward_function --name "ed_airl_maze_iter3" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_4/ed_airl_maze_run3/best_guess_reward_function --name "ed_airl_maze_iter4" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_5/ed_airl_maze_run3/best_guess_reward_function --name "ed_airl_maze_iter5" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_6/ed_airl_maze_run3/best_guess_reward_function --name "ed_airl_maze_iter6" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_7/ed_airl_maze_run3/best_guess_reward_function --name "ed_airl_maze_iter7" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_8/ed_airl_maze_run3/best_guess_reward_function --name "ed_airl_maze_iter8" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_9/ed_airl_maze_run3/best_guess_reward_function --name "ed_airl_maze_iter9" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10

python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_0/ed_airl_maze_run4/single_env_reward_function --name "ed_airl_maze_iter0" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_1/ed_airl_maze_run4/best_guess_reward_function --name "ed_airl_maze_iter1" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_2/ed_airl_maze_run4/best_guess_reward_function --name "ed_airl_maze_iter2" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_3/ed_airl_maze_run4/best_guess_reward_function --name "ed_airl_maze_iter3" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_4/ed_airl_maze_run4/best_guess_reward_function --name "ed_airl_maze_iter4" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_5/ed_airl_maze_run4/best_guess_reward_function --name "ed_airl_maze_iter5" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_6/ed_airl_maze_run4/best_guess_reward_function --name "ed_airl_maze_iter6" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_7/ed_airl_maze_run4/best_guess_reward_function --name "ed_airl_maze_iter7" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_8/ed_airl_maze_run4/best_guess_reward_function --name "ed_airl_maze_iter8" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_9/ed_airl_maze_run4/best_guess_reward_function --name "ed_airl_maze_iter9" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10

python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_0/ed_airl_maze_run5/single_env_reward_function --name "ed_airl_maze_iter0" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_1/ed_airl_maze_run5/best_guess_reward_function --name "ed_airl_maze_iter1" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_2/ed_airl_maze_run5/best_guess_reward_function --name "ed_airl_maze_iter2" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_3/ed_airl_maze_run5/best_guess_reward_function --name "ed_airl_maze_iter3" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_4/ed_airl_maze_run5/best_guess_reward_function --name "ed_airl_maze_iter4" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_5/ed_airl_maze_run5/best_guess_reward_function --name "ed_airl_maze_iter5" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_6/ed_airl_maze_run5/best_guess_reward_function --name "ed_airl_maze_iter6" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_7/ed_airl_maze_run5/best_guess_reward_function --name "ed_airl_maze_iter7" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_8/ed_airl_maze_run5/best_guess_reward_function --name "ed_airl_maze_iter8" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
#python3 -m test eval_on --env MazeED --env_set demo --from_path checkpoints/irl/ed_AIRL/iter_9/ed_airl_maze_run5/best_guess_reward_function --name "ed_airl_maze_iter9" --max_iter 45 --irl_algo "MULTI_AIRL"  --timelimit 250 --timelimit_noise 10
