#
#
#python3 -m main visualize_expert --env MazeED --design demo=0 --deterministic 0 --record_gifs "mazes/maze_0"
#python3 -m main visualize_expert --env MazeED --design demo=1 --deterministic 0 --record_gifs "mazes/maze_1"
#python3 -m main visualize_expert --env MazeED --design demo=2 --deterministic 0 --record_gifs "mazes/maze_2"
#python3 -m main visualize_expert --env MazeED --design demo=3 --deterministic 0 --record_gifs "mazes/maze_3"
#python3 -m main visualize_expert --env MazeED --design demo=4 --deterministic 0 --record_gifs "mazes/maze_4"
#python3 -m main visualize_expert --env MazeED --design demo=5 --deterministic 0 --record_gifs "mazes/maze_5"
#python3 -m main visualize_expert --env MazeED --design demo=6 --deterministic 0 --record_gifs "mazes/maze_6"
#python3 -m main visualize_expert --env MazeED --design demo=7 --deterministic 0 --record_gifs "mazes/maze_7"
#python3 -m main visualize_expert --env MazeED --design demo=8 --deterministic 0 --record_gifs "mazes/maze_8"
#python3 -m main visualize_expert --env MazeED --design demo=9 --deterministic 0 --record_gifs "mazes/maze_9"
#python3 -m main visualize_expert --env MazeED --design demo=10 --deterministic 0 --record_gifs "mazes/maze_10"
#python3 -m main visualize_expert --env MazeED --design demo=11 --deterministic 0 --record_gifs "mazes/maze_11"
#python3 -m main visualize_expert --env MazeED --design demo=12 --deterministic 0 --record_gifs "mazes/maze_12"
#python3 -m main visualize_expert --env MazeED --design demo=13 --deterministic 0 --record_gifs "mazes/maze_13"
#python3 -m main visualize_expert --env MazeED --design demo=14 --deterministic 0 --record_gifs "mazes/maze_14"
#python3 -m main visualize_expert --env MazeED --design demo=15 --deterministic 0 --record_gifs "mazes/maze_15"
#python3 -m main visualize_expert --env MazeED --design demo=16 --deterministic 0 --record_gifs "mazes/maze_16"
#python3 -m main visualize_expert --env MazeED --design demo=17 --deterministic 0 --record_gifs "mazes/maze_17"
#python3 -m main visualize_expert --env MazeED --design demo=18 --deterministic 0 --record_gifs "mazes/maze_18"
#
#python3 -m main visualize_expert --env MazeED --design test=0 --deterministic 0 --record_gifs "mazes/maze_20"
#python3 -m main visualize_expert --env MazeED --design test=2 --deterministic 0 --record_gifs "mazes/maze_22"
#python3 -m main visualize_expert --env MazeED --design test=3 --deterministic 0 --record_gifs "mazes/maze_23"
#python3 -m main visualize_expert --env MazeED --design test=4 --deterministic 0 --record_gifs "mazes/maze_24"
#python3 -m main visualize_expert --env MazeED --design test=7 --deterministic 0 --record_gifs "mazes/maze_27"
#python3 -m main visualize_expert --env MazeED --design test=9 --deterministic 0 --record_gifs "mazes/maze_29"

python3 -m main visualize_expert --env MazeED --design test=1 --deterministic 0 --record_gifs "mazes/maze_21"
python3 -m main visualize_expert --env MazeED --design test=5 --deterministic 0 --record_gifs "mazes/maze_25"
python3 -m main visualize_expert --env MazeED --design test=6 --deterministic 0 --record_gifs "mazes/maze_26"
python3 -m main visualize_expert --env MazeED --design test=8 --deterministic 0 --record_gifs "mazes/maze_28"

